// src/lib/components/ActionButton.tsx
import type { JSX } from 'solid-js';

export interface ActionButtonProps {
  type?: 'button' | 'submit';
  tone?: 'primary' | 'quiet' | 'danger';
  disabled?: boolean;
  title?: string;
  onClick?: JSX.EventHandlerUnion<HTMLButtonElement, MouseEvent>;
  children: JSX.Element;
}

export default function ActionButton(props: ActionButtonProps) {
  return (
    <button
      type={props.type ?? 'button'}
      class="action"
      classList={{
        primary: props.tone === 'primary',
        danger: props.tone === 'danger'
      }}
      disabled={props.disabled ?? false}
      title={props.title}
      onClick={props.onClick}
    >
      {props.children}
    </button>
  );
}

// src/lib/components/ActionButton.svelte
<script lang="ts">
  let {
    type = 'button',
    tone = 'quiet',
    disabled = false,
    title,
    onclick,
    children
  }: {
    type?: 'button' | 'submit';
    tone?: 'primary' | 'quiet' | 'danger';
    disabled?: boolean;
    title?: string;
    onclick?: (event: MouseEvent) => void;
    children: import('svelte').Snippet;
  } = $props();
</script>

<button {type} class:primary={tone === 'primary'} class:danger={tone === 'danger'} class="action" {disabled} {title} {onclick}>
  {@render children()}
</button>
