// src/lib/components/Sidebar.tsx
import { For, Show, createSignal } from 'solid-js';
import type { Collection, HistoryEntry, RequestDraft } from '../types';
import { formatTime } from '../utils';
import ActionButton from './ActionButton';

type SidebarMode = 'workspace' | 'history' | 'environments';
type SelectableSidebarMode = Exclude<SidebarMode, 'environments'>;

export interface SidebarProps {
  collections: Collection[];
  requests: RequestDraft[];
  history: HistoryEntry[];
  mode: SidebarMode;
  selectedRequestId: string | null;
  selectedHistoryId: string | null;
  onMode: (mode: SelectableSidebarMode) => void;
  onRequest: (id: string) => void;
  onHistory: (id: string) => void;
  onNewCollection: () => void;
  onNewRequest: (collectionId: string | null) => void;
  onSaveCollection: (collection: Collection) => void;
  onDeleteCollection: (collection: Collection) => void;
  onDeleteRequest: (request: RequestDraft) => void;
  onClearHistory: () => void;
}

export default function Sidebar(props: SidebarProps) {
  const [expanded, setExpanded] = createSignal<Record<string, boolean>>({});

  const isExpanded = (collectionId: string) => expanded()[collectionId] !== false;

  return (
    <aside class="sidebar">
      <nav class="sidebar-tabs" aria-label="Workspace navigation">
        <button
          classList={{ active: props.mode === 'workspace' }}
          onClick={() => props.onMode('workspace')}
        >
          Workspace
        </button>
        <button
          classList={{ active: props.mode === 'history' }}
          onClick={() => props.onMode('history')}
        >
          History
        </button>
      </nav>

      <Show
        when={props.mode === 'history'}
        fallback={
          <>
            <div class="sidebar-section-head">
              <span>COLLECTIONS</span>
              <ActionButton onClick={props.onNewCollection} title="New collection">
                ＋
              </ActionButton>
            </div>
            <div class="tree-scroll">
              <For each={props.collections}>
                {(collection) => (
                  <section class="collection-node">
                    <div class="collection-row">
                      <button
                        class="disclosure"
                        aria-label={`${isExpanded(collection.id) ? 'Collapse' : 'Expand'} ${collection.name}`}
                        onClick={() =>
                          setExpanded((current) => ({
                            ...current,
                            [collection.id]: !isExpanded(collection.id)
                          }))
                        }
                      >
                        ▾
                      </button>
                      <input
                        value={collection.name}
                        aria-label="Collection name"
                        onBlur={(event) => props.onSaveCollection({ ...collection, name: event.currentTarget.value })}
                        onKeyDown={(event) => {
                          if (event.key === 'Enter') event.currentTarget.blur();
                        }}
                      />
                      <button
                        class="icon-button"
                        title="New request"
                        aria-label={`New request in ${collection.name}`}
                        onClick={() => props.onNewRequest(collection.id)}
                      >
                        ＋
                      </button>
                      <button
                        class="icon-button danger-icon"
                        title="Delete collection"
                        aria-label={`Delete ${collection.name}`}
                        onClick={() => props.onDeleteCollection(collection)}
                      >
                        ×
                      </button>
                    </div>
                    <Show when={isExpanded(collection.id)}>
                      <div class="request-tree">
                        <For
                          each={props.requests.filter(
                            (request) => request.collectionId === collection.id
                          )}
                          fallback={
                            <button class="add-first" onClick={() => props.onNewRequest(collection.id)}>
                              ＋ Add first request
                            </button>
                          }
                        >
                          {(request) => (
                            <div
                              class="tree-request"
                              classList={{ active: request.id === props.selectedRequestId }}
                            >
                              <button onClick={() => props.onRequest(request.id)}>
                                <span
                                  class={`method-dot method-${request.method.toLowerCase()}`}
                                ></span>
                                <span>{request.name}</span>
                              </button>
                              <button
                                class="icon-button danger-icon"
                                aria-label={`Delete ${request.name}`}
                                title="Delete request"
                                onClick={() => props.onDeleteRequest(request)}
                              >
                                ×
                              </button>
                            </div>
                          )}
                        </For>
                      </div>
                    </Show>
                  </section>
                )}
              </For>

              <section class="collection-node unfiled">
                <div class="collection-row">
                  <span class="disclosure">⌁</span>
                  <span class="collection-label">Unfiled</span>
                  <button
                    class="icon-button"
                    title="New unfiled request"
                    aria-label="New unfiled request"
                    onClick={() => props.onNewRequest(null)}
                  >
                    ＋
                  </button>
                </div>
                <div class="request-tree">
                  <For
                    each={props.requests.filter((request) => request.collectionId === null)}
                    fallback={
                      <button class="add-first" onClick={() => props.onNewRequest(null)}>
                        ＋ New request
                      </button>
                    }
                  >
                    {(request) => (
                      <div
                        class="tree-request"
                        classList={{ active: request.id === props.selectedRequestId }}
                      >
                        <button onClick={() => props.onRequest(request.id)}>
                          <span
                            class={`method-dot method-${request.method.toLowerCase()}`}
                          ></span>
                          <span>{request.name}</span>
                        </button>
                        <button
                          class="icon-button danger-icon"
                          aria-label={`Delete ${request.name}`}
                          title="Delete request"
                          onClick={() => props.onDeleteRequest(request)}
                        >
                          ×
                        </button>
                      </div>
                    )}
                  </For>
                </div>
              </section>
            </div>
          </>
        }
      >
        <div class="sidebar-section-head">
          <span>{props.history.length} RECORDS</span>
          <Show when={props.history.length > 0}>
            <button onClick={props.onClearHistory}>Clear</button>
          </Show>
        </div>
        <div class="tree-scroll">
          <Show
            when={props.history.length > 0}
            fallback={
              <div class="sidebar-empty">
                <strong>No recorded flights</strong>
                <span>Completed requests appear here and persist across restarts.</span>
              </div>
            }
          >
            <For each={props.history}>
              {(entry) => (
                <button
                  class="history-item"
                  classList={{ active: entry.id === props.selectedHistoryId }}
                  onClick={() => props.onHistory(entry.id)}
                >
                  <span class={`method-tag method-${entry.method.toLowerCase()}`}>{entry.method}</span>
                  <span class="history-copy">
                    <strong>{entry.requestName}</strong>
                    <small>
                      {entry.response.status ?? 'ERR'} · {formatTime(entry.executedAt)}
                    </small>
                  </span>
                </button>
              )}
            </For>
          </Show>
        </div>
      </Show>
    </aside>
  );
}

// src/lib/components/Sidebar.svelte
<script lang="ts">
  import type { Collection, HistoryEntry, RequestDraft } from '../types';
  import { formatTime } from '../utils';
  import ActionButton from './ActionButton.svelte';

  let {
    collections,
    requests,
    history,
    mode,
    selectedRequestId,
    selectedHistoryId,
    onmode,
    onrequest,
    onhistory,
    onnewcollection,
    onnewrequest,
    onsavecollection,
    ondeletecollection,
    ondeleterequest,
    onclearhistory
  }: {
    collections: Collection[];
    requests: RequestDraft[];
    history: HistoryEntry[];
    mode: 'workspace' | 'history' | 'environments';
    selectedRequestId: string | null;
    selectedHistoryId: string | null;
    onmode: (mode: 'workspace' | 'history') => void;
    onrequest: (id: string) => void;
    onhistory: (id: string) => void;
    onnewcollection: () => void;
    onnewrequest: (collectionId: string | null) => void;
    onsavecollection: (collection: Collection) => void;
    ondeletecollection: (collection: Collection) => void;
    ondeleterequest: (request: RequestDraft) => void;
    onclearhistory: () => void;
  } = $props();

  let expanded = $state<Record<string, boolean>>({});
</script>

<aside class="sidebar">
  <nav class="sidebar-tabs" aria-label="Workspace navigation">
    <button class:active={mode === 'workspace'} onclick={() => onmode('workspace')}>Workspace</button>
    <button class:active={mode === 'history'} onclick={() => onmode('history')}>History</button>
  </nav>

  {#if mode === 'history'}
    <div class="sidebar-section-head"><span>{history.length} RECORDS</span>{#if history.length}<button onclick={onclearhistory}>Clear</button>{/if}</div>
    <div class="tree-scroll">
      {#each history as entry (entry.id)}
        <button class="history-item" class:active={entry.id === selectedHistoryId} onclick={() => onhistory(entry.id)}>
          <span class={`method-tag method-${entry.method.toLowerCase()}`}>{entry.method}</span>
          <span class="history-copy"><strong>{entry.requestName}</strong><small>{entry.response.status ?? 'ERR'} · {formatTime(entry.executedAt)}</small></span>
        </button>
      {:else}
        <div class="sidebar-empty"><strong>No recorded flights</strong><span>Completed requests appear here and persist across restarts.</span></div>
      {/each}
    </div>
  {:else}
    <div class="sidebar-section-head"><span>COLLECTIONS</span><ActionButton onclick={onnewcollection} title="New collection">＋</ActionButton></div>
    <div class="tree-scroll">
      {#each collections as collection (collection.id)}
        <section class="collection-node">
          <div class="collection-row">
            <button class="disclosure" aria-label={`${expanded[collection.id] === false ? 'Expand' : 'Collapse'} ${collection.name}`} onclick={() => expanded[collection.id] = expanded[collection.id] === false}>▾</button>
            <input bind:value={collection.name} aria-label="Collection name" onblur={() => onsavecollection(collection)} onkeydown={(event) => event.key === 'Enter' && event.currentTarget.blur()} />
            <button class="icon-button" title="New request" aria-label={`New request in ${collection.name}`} onclick={() => onnewrequest(collection.id)}>＋</button>
            <button class="icon-button danger-icon" title="Delete collection" aria-label={`Delete ${collection.name}`} onclick={() => ondeletecollection(collection)}>×</button>
          </div>
          {#if expanded[collection.id] !== false}
            <div class="request-tree">
              {#each requests.filter((request) => request.collectionId === collection.id) as request (request.id)}
                <div class="tree-request" class:active={request.id === selectedRequestId}>
                  <button onclick={() => onrequest(request.id)}><span class={`method-dot method-${request.method.toLowerCase()}`}></span><span>{request.name}</span></button>
                  <button class="icon-button danger-icon" aria-label={`Delete ${request.name}`} title="Delete request" onclick={() => ondeleterequest(request)}>×</button>
                </div>
              {:else}<button class="add-first" onclick={() => onnewrequest(collection.id)}>＋ Add first request</button>{/each}
            </div>
          {/if}
        </section>
      {/each}

      <section class="collection-node unfiled">
        <div class="collection-row"><span class="disclosure">⌁</span><span class="collection-label">Unfiled</span><button class="icon-button" title="New unfiled request" aria-label="New unfiled request" onclick={() => onnewrequest(null)}>＋</button></div>
        <div class="request-tree">
          {#each requests.filter((request) => request.collectionId === null) as request (request.id)}
            <div class="tree-request" class:active={request.id === selectedRequestId}>
              <button onclick={() => onrequest(request.id)}><span class={`method-dot method-${request.method.toLowerCase()}`}></span><span>{request.name}</span></button>
              <button class="icon-button danger-icon" aria-label={`Delete ${request.name}`} title="Delete request" onclick={() => ondeleterequest(request)}>×</button>
            </div>
          {:else}<button class="add-first" onclick={() => onnewrequest(null)}>＋ New request</button>{/each}
        </div>
      </section>
    </div>
  {/if}
</aside>
